apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: strimzi-cluster
  name: derived-stories
spec:
  config:
    max.message.bytes: "10485760"
    retention.ms: "1800000"
    segment.bytes: "1073741824"
  partitions: 1
  replicas: 1
  topicName: derived-stories
