apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: strimzi-cluster
    manager: okhttp
  name: windowed-logs-1000-1000
spec:
  config:
    max.message.bytes: "1048588"
    retention.ms: "1800000"
    segment.bytes: "1073741824"
  partitions: 1
  replicas: 1
  topicName: windowed-logs-1000-1000
